DROP TABLE LOS_OPTIMISTAS.Usuario_Rol

DROP TABLE LOS_OPTIMISTAS.Rol_Funcionalidad

DROP TABLE LOS_OPTIMISTAS.Funcionalidad

DROP TABLE LOS_OPTIMISTAS.Rol

DROP TABLE LOS_OPTIMISTAS.Empresa

DROP TABLE LOS_OPTIMISTAS.Cliente

DROP TABLE LOS_OPTIMISTAS.Tipo_Documento

DROP TABLE LOS_OPTIMISTAS.Dom_Mail

DROP TABLE LOS_OPTIMISTAS.Rubro_Publicacion

DROP TABLE LOS_OPTIMISTAS.Rubro

DROP TABLE LOS_OPTIMISTAS.Estado_Publicacion

DROP TABLE LOS_OPTIMISTAS.Estado

DROP TABLE LOS_OPTIMISTAS.Publicacion_Calificaciones

DROP TABLE LOS_OPTIMISTAS.Publicacion_Preguntas

DROP TABLE LOS_OPTIMISTAS.Historial_Subasta

DROP TABLE LOS_OPTIMISTAS.Facturacion_Pendiente



DROP TABLE LOS_OPTIMISTAS.Publicacion

DROP TABLE LOS_OPTIMISTAS.Visibilidad

DROP TABLE LOS_OPTIMISTAS.Tipo_Publicacion

DROP TABLE LOS_OPTIMISTAS.Stock

DROP TABLE LOS_OPTIMISTAS.Forma_Pago

DROP TABLE LOS_OPTIMISTAS.Tipo_Pago

DROP TABLE LOS_OPTIMISTAS.Detalle_Tarjeta

DROP TABLE LOS_OPTIMISTAS.Facturacion

DROP TABLE LOS_OPTIMISTAS.Usuario

DROP FUNCTION LOS_OPTIMISTAS.obtenerDNI

DROP FUNCTION LOS_OPTIMISTAS.obtenerCuit

DROP FUNCTION LOS_OPTIMISTAS.obtenerCodigoArticulo


DROP FUNCTION LOS_OPTIMISTAS.obtenerCondicionPreguntas

DROP FUNCTION LOS_OPTIMISTAS.obtenerIdTipoPublicacion

DROP PROCEDURE LOS_OPTIMISTAS.proc_ListarClientes

DROP PROCEDURE LOS_OPTIMISTAS.proc_ListarEmpresas

DROP PROCEDURE LOS_OPTIMISTAS.ListarRoles

DROP PROCEDURE LOS_OPTIMISTAS.AltaCliente

DROP PROCEDURE LOS_OPTIMISTAS.BajaUsuario

DROP PROCEDURE LOS_OPTIMISTAS.AltaEmpresa

DROP PROCEDURE LOS_OPTIMISTAS.ModificarCliente

DROP PROCEDURE LOS_OPTIMISTAS.ModificarEmpresa

DROP SCHEMA LOS_OPTIMISTAS