DROP TABLE LOS_OPTIMISTAS.Usuario_Rol

DROP TABLE LOS_OPTIMISTAS.Rol_Funcionalidad

DROP TABLE LOS_OPTIMISTAS.Funcionalidad

DROP TABLE LOS_OPTIMISTAS.Rol

DROP TABLE LOS_OPTIMISTAS.Empresa

DROP TABLE LOS_OPTIMISTAS.Cliente

DROP TABLE LOS_OPTIMISTAS.Tipo_Documento

DROP TABLE LOS_OPTIMISTAS.Dom_Mail

DROP TABLE LOS_OPTIMISTAS.Rubro_Publicacion

DROP TABLE LOS_OPTIMISTAS.Rubro

DROP TABLE LOS_OPTIMISTAS.Estado_Publicacion

DROP TABLE LOS_OPTIMISTAS.Estado

DROP TABLE LOS_OPTIMISTAS.Publicacion_Calificaciones

DROP TABLE LOS_OPTIMISTAS.Publicacion_Preguntas

DROP TABLE LOS_OPTIMISTAS.Historial_Subasta

DROP TABLE LOS_OPTIMISTAS.Publicacion

DROP TABLE LOS_OPTIMISTAS.Visibilidad

DROP TABLE LOS_OPTIMISTAS.Tipo_Publicacion

DROP TABLE LOS_OPTIMISTAS.Stock

DROP TABLE LOS_OPTIMISTAS.Usuario

DROP FUNCTION LOS_OPTIMISTAS.obtenerDNI

DROP FUNCTION LOS_OPTIMISTAS.obtenerCuit

DROP FUNCTION LOS_OPTIMISTAS.obtenerCodigoArticulo

DROP FUNCTION LOS_OPTIMISTAS.obtenerCondicionPreguntas

DROP SCHEMA LOS_OPTIMISTAS
