DROP TABLE LOS_OPTIMISTAS.Usuario_Rol

DROP TABLE LOS_OPTIMISTAS.Rol_Funcionalidad

DROP TABLE LOS_OPTIMISTAS.Funcionalidad

DROP TABLE LOS_OPTIMISTAS.Rol

DROP TABLE LOS_OPTIMISTAS.Empresa

DROP TABLE LOS_OPTIMISTAS.Cliente

DROP TABLE LOS_OPTIMISTAS.Dom_Mail

DROP TABLE LOS_OPTIMISTAS.publicacion

DROP TABLE LOS_OPTIMISTAS.publicacion_calificaciones

DROP TABLE LOS_OPTIMISTAS.Usuario

DROP FUNCTION LOS_OPTIMISTAS.obtenerDNI

DROP FUNCTION LOS_OPTIMISTAS.obtenerCuit

DROP FUNCTION LOS_OPTIMISTAS.obtenerCodigoArticulo

DROP FUNCTION LOS_OPTIMISTAS.obtenerCondicionPreguntas

DROP SCHEMA LOS_OPTIMISTAS
